baseURL          = "http://localhost:1313/"
disableKinds      =["RSS", "sitemap"]
languageCode     = "en-us"
title            = "Jenna Hines"
relativeURLs     = true
sectionPagesMenu = "main"

[params]
    cloudinary = "http://res.cloudinary.com/jennahines/image/upload"