backend:
  name: git-gateway
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

collections:
  - name: "photo-albums" # Used in routes, e.g., /admin/collections/blog
    label: "Photo Albums" # Used in the UI
    folder: "content/photo-albums" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # - {label: "Description", name: "description", widget: "string"}
      # - {label: "location", name: "location", widget: "string"}
      - {label: "Cloudinary Album Folder Name", name: "albumfolder", widget: "string"}
      - {label: "Featured Image Filename", name: "featuredimage", widget: "string"}
      - label: "Body"
        name: "body"
        widget: "text"
        # fields: 
        # - label: "Album Items"
        #   name: "albumfigure"
        #   widget: "list"
        #   allow_add: true
        #   fields:
        #     - {label: "Filename", name: "file", widget: "string"}
        #     - {label: "Image Size", name: "size", widget: "string", default: "1400x933"}
        #     - {label: "Caption", name: "caption", widget: "string"}